version: "3"

services:
  db:
    image: postgres:latest
    container_name: "markets-database"
    restart: always
    environment: 
      POSTGRES_PASSWORD: teste
      POSTGRES_USER: teste
      POSTGRES_MULTIPLE_DATABASES: markets, marketsteste
    ports: 
      - "5432:5432"
    networks:
      - apis
    volumes: 
      - database_postgres:/var/lib/postgresql/data

  api:
    build: .
    container_name: "farmers-markets-api"
    environment: 
      PSQL_USERNAME: "teste"
      PSQL_PASSWORD: "teste"
      PSQL_DATABASE: "markets"
      PSQL_HOSTNAME: "db"
      PSQL_PORT: "5432"
    ports:
      - "8080:8080"
    depends_on: 
      - db
    networks: 
      - apis

volumes: 
  database_postgres:

networks: 
  apis:
    driver: bridge